// Code by Gustav Reinehr

// Country codes and mask patterns.
function maskPhoneNumber(inputs) {
    const maskList = [
    // 1
    { "code": "+1", "pattern": "### ### ####" },
    // 2
    { "code": "+20", "pattern": "### ### ####" },
    { "code": "+211", "pattern": "## ### ####" },
    { "code": "+212", "pattern": "## #### ###" },
    { "code": "+213", "pattern": "## ### ####" },
    { "code": "+216", "pattern": "## ### ###" },
    { "code": "+218", "pattern": "## ### ###" },
    { "code": "+218", "pattern": "21 ### ####" },
    { "code": "+220", "pattern": "### ## ##" },
    { "code": "+221", "pattern": "## ### ####" },
    { "code": "+222", "pattern": "## ## ####" },
    { "code": "+223", "pattern": "## ## ####" },
    { "code": "+224", "pattern": "## ### ###" },
    { "code": "+225", "pattern": "## ### ###" },
    { "code": "+226", "pattern": "## ## ####" },
    { "code": "+227", "pattern": "## ## ####" },
    { "code": "+228", "pattern": "## ### ###" },
    { "code": "+229", "pattern": "## ## ####" },
    { "code": "+230", "pattern": "### ####" },
    { "code": "+231", "pattern": "## ### ###" },
    { "code": "+232", "pattern": "## ######" },
    { "code": "+233", "pattern": "### ### ###" },
    { "code": "+234", "pattern": "## ### ##" },
    { "code": "+234", "pattern": "## ### ###" },
    { "code": "+234", "pattern": "### ### ####" },
    { "code": "+235", "pattern": "## ## ## ##" },
    { "code": "+236", "pattern": "## ## ####" },
    { "code": "+237", "pattern": "#### ####" },
    { "code": "+238", "pattern": "### ## ##" },
    { "code": "+239", "pattern": "## #####" },
    { "code": "+240", "pattern": "## ### ####" },
    { "code": "+241", "pattern": "# ## ## ##" },
    { "code": "+242", "pattern": "## ### ####" },
    { "code": "+243", "pattern": "### ### ###" },
    { "code": "+244", "pattern": "### ### ###" },
    { "code": "+245", "pattern": "# ######" },
    { "code": "+246", "pattern": "### ####" },
    { "code": "+247", "pattern": "####" },
    { "code": "+248", "pattern": "# ### ###" },
    { "code": "+249", "pattern": "## ### ####" },
    { "code": "+250", "pattern": "### ### ###" },
    { "code": "+251", "pattern": "## ### ####" },
    { "code": "+252", "pattern": "# ### ###" },
    { "code": "+252", "pattern": "## ### ###" },
    { "code": "+253", "pattern": "## ## ## ##" },
    { "code": "+254", "pattern": "### ######" },
    { "code": "+255", "pattern": "## ### ####" },
    { "code": "+256", "pattern": "### ### ###" },
    { "code": "+257", "pattern": "## ## ####" },
    { "code": "+258", "pattern": "## ### ###" },
    { "code": "+260", "pattern": "## ### ####" },
    { "code": "+261", "pattern": "## ## #####" },
    { "code": "+262", "pattern": "##### ####" },
    { "code": "+263", "pattern": "# ######" },
    { "code": "+264", "pattern": "## ### ####" },
    { "code": "+265", "pattern": "1 ### ###" },
    { "code": "+265", "pattern": "# #### ####" },
    { "code": "+266", "pattern": "# ### ####" },
    { "code": "+267", "pattern": "## ### ###" },
    { "code": "+268", "pattern": "## ## ####" },
    { "code": "+269", "pattern": "## #####" },
    { "code": "+27", "pattern": "## ### ####" },
    { "code": "+290", "pattern": "#####" },
    { "code": "+291", "pattern": "# ### ###" },
    { "code": "+297", "pattern": "### ####" },
    { "code": "+298", "pattern": "### ###" },
    { "code": "+299", "pattern": "## ## ##" },
    // 3
    { "code": "+30", "pattern": "### ### ####" },
    { "code": "+31", "pattern": "## ### ####" },
    { "code": "+32", "pattern": "### ### ###" },
    { "code": "+33", "pattern": "### ### ###" },
    { "code": "+34", "pattern": "### ### ###" },
    { "code": "+350", "pattern": "### #####" },
    { "code": "+351", "pattern": "## ### ####" },
    { "code": "+352", "pattern": "### ### ###" },
    { "code": "+353", "pattern": "### ### ###" },
    { "code": "+354", "pattern": "### ####" },
    { "code": "+355", "pattern": "### ### ###" },
    { "code": "+356", "pattern": "#### ####" },
    { "code": "+357", "pattern": "## ### ###" },
    { "code": "+358", "pattern": "### ### ## ##" },
    { "code": "+359", "pattern": "### ### ###" },
    { "code": "+36", "pattern": "### ### ###" },
    { "code": "+370", "pattern": "### ## ###" },
    { "code": "+371", "pattern": "## ### ###" },
    { "code": "+372", "pattern": "### ####" },
    { "code": "+372", "pattern": "#### ####" },
    { "code": "+373", "pattern": "#### ####" },
    { "code": "+375", "pattern": "## ### ## ##" },
    { "code": "+374", "pattern": "## ### ###" },
    { "code": "+376", "pattern": "### ###" },
    { "code": "+377", "pattern": "## ### ###" },
    { "code": "+377", "pattern": "### ### ###" },
    { "code": "+378", "pattern": "#### ######" },
    { "code": "+380", "pattern": "## ### ## ##" },
    { "code": "+381", "pattern": "## ### ####" },
    { "code": "+382", "pattern": "## ### ###" },
    { "code": "+385", "pattern": "## ### ###" },
    { "code": "+386", "pattern": "## ### ###" },
    { "code": "+387", "pattern": "## ####" },
    { "code": "+387", "pattern": "## #####" },
    { "code": "+389", "pattern": "## ### ###" },
    { "code": "+39", "pattern": "6 698 #####" },
    { "code": "+39", "pattern": "### #### ###" },
    //4
    { "code": "+40", "pattern": "## ### ####" },
    { "code": "+41", "pattern": "## ### ####" },
    { "code": "+420", "pattern": "### ### ###" },
    { "code": "+421", "pattern": "### ### ###" },
    { "code": "+423", "pattern": "### ### ####" },
    { "code": "+43", "pattern": "### ### ####" },
    { "code": "+44", "pattern": "## #### ####" },
    { "code": "+45", "pattern": "## ## ## ##" },
    { "code": "+46", "pattern": "## ### ####" },
    { "code": "+47", "pattern": "### ## ###" },
    { "code": "+48", "pattern": "### ### ###" },
    { "code": "+49", "pattern": "### ###" },
    { "code": "+49", "pattern": "### ## ##" },
    { "code": "+49", "pattern": "### ## ###" },
    { "code": "+49", "pattern": "### ## ####" },
    { "code": "+49", "pattern": "### ### ####" },
    { "code": "+49", "pattern": "#### ### ####" },
    // 5
    { "code": "+500", "pattern": "#####" },
    { "code": "+501", "pattern": "### ####" },
    { "code": "+502", "pattern": "# ### ####" },
    { "code": "+503", "pattern": "## ## ####" },
    { "code": "+504", "pattern": "#### ####" },
    { "code": "+505", "pattern": "#### ####" },
    { "code": "+506", "pattern": "#### ####" },
    { "code": "+507", "pattern": "### ####" },
    { "code": "+508", "pattern": "## ####" },
    { "code": "+509", "pattern": "## ## ####" },
    { "code": "+51", "pattern": "### ### ###" },
    { "code": "+52", "pattern": "## ## ####" },
    { "code": "+52", "pattern": "### ### ####" },
    { "code": "+53", "pattern": "# ### ####" },
    { "code": "+54", "pattern": "### ### ####" },
    { "code": "+55", "pattern": "## #### ####" },
    { "code": "+55", "pattern": "## 9#### ####" },
    { "code": "+56", "pattern": "# #### ####" },
    { "code": "+57", "pattern": "### ### ####" },
    { "code": "+58", "pattern": "### ### ####" },
    { "code": "+590", "pattern": "### ### ###" },
    { "code": "+591", "pattern": "# ### ####" },
    { "code": "+592", "pattern": "### ####" },
    { "code": "+593", "pattern": "# ### ####" },
    { "code": "+593", "pattern": "## ### ####" },
    { "code": "+594", "pattern": "##### ####" },
    { "code": "+595", "pattern": "### ### ###" },
    { "code": "+596", "pattern": "### ## ## ##" },
    { "code": "+597", "pattern": "### ###" },
    { "code": "+597", "pattern": "### ####" },
    { "code": "+598", "pattern": "# ### ## ##" },
    { "code": "+599", "pattern": "### ####" },
    { "code": "+599", "pattern": "9### ####" },
    // 6
    { "code": "+60", "pattern": "# ### ###" },
    { "code": "+60", "pattern": "## ### ###" },
    { "code": "+60", "pattern": "## ### ####" },
    { "code": "+61", "pattern": "# #### ####" },
    { "code": "+62", "pattern": "## ### ##" },
    { "code": "+62", "pattern": "## ### ###" },
    { "code": "+62", "pattern": "## ### ####" },
    { "code": "+62", "pattern": "8## ### ###" },
    { "code": "+62", "pattern": "8## ### ####" },
    { "code": "+62", "pattern": "8## ### ## ###" },
    { "code": "+63", "pattern": "### ### ####" },
    { "code": "+64", "pattern": "## ### ###" },
    { "code": "+64", "pattern": "### ### ###" },
    { "code": "+64", "pattern": "### ### ####" },
    { "code": "+65", "pattern": "#### ####" },
    { "code": "+66", "pattern": "## ### ###" },
    { "code": "+66", "pattern": "## ### ####" },
    { "code": "+670", "pattern": "### ####" },
    { "code": "+670", "pattern": "77# #####" },
    { "code": "+670", "pattern": "78# #####" },
    { "code": "+672", "pattern": "1## ###" },
    { "code": "+672", "pattern": "3## ###" },
    { "code": "+673", "pattern": "### ####" },
    { "code": "+674", "pattern": "### ####" },
    { "code": "+675", "pattern": "### ## ###" },
    { "code": "+676", "pattern": "#####" },
    { "code": "+677", "pattern": "#####" },
    { "code": "+677", "pattern": "### ####" },
    { "code": "+678", "pattern": "#####" },
    { "code": "+678", "pattern": "## #####" },
    { "code": "+679", "pattern": "## #####" },
    { "code": "+680", "pattern": "### ####" },
    { "code": "+681", "pattern": "## ####" },
    { "code": "+682", "pattern": "## ###" },
    { "code": "+683", "pattern": "####" },
    { "code": "+685", "pattern": "## ####" },
    { "code": "+686", "pattern": "## ###" },
    { "code": "+687", "pattern": "## ####" },
    { "code": "+688 2", "pattern": "####" },
    { "code": "+688 90", "pattern": "####" },
    { "code": "+689", "pattern": "## ## ##" },
    { "code": "+690", "pattern": "#####" },
    { "code": "+691", "pattern": "### ####" },
    { "code": "+692", "pattern": "### ####" },
    // 7
    { "code": "+7", "pattern": "### ### ## ##" },
    { "code": "+7", "pattern": "6## ### ## ##" },
    { "code": "+7", "pattern": "7## ### ## ##" },
    // 8
    { "code": "+81", "pattern": "### ### ###" },
    { "code": "+81", "pattern": "## #### ####" },
    { "code": "+82", "pattern": "## ### ####" },
    { "code": "+84", "pattern": "## #### ###" },
    { "code": "+84", "pattern": "### #### ###" },
    { "code": "+850", "pattern": "### ###" },
    { "code": "+850", "pattern": "#### ####" },
    { "code": "+850", "pattern": "## ### ###" },
    { "code": "+850", "pattern": "### #### ###" },
    { "code": "+850", "pattern": "191 ### ####" },
    { "code": "+850", "pattern": "#### #############" },
    { "code": "+852", "pattern": "#### ####" },
    { "code": "+853", "pattern": "#### ####" },
    { "code": "+855", "pattern": "## ### ###" },
    { "code": "+856", "pattern": "## ### ###" },
    { "code": "+856", "pattern": "20## ### ###" },
    { "code": "+86", "pattern": "### #### ###" },
    { "code": "+86", "pattern": "### #### ####" },
    { "code": "+86", "pattern": "## ##### #####" },
    { "code": "+880", "pattern": "## ### ###" },
    { "code": "+886", "pattern": "#### ####" },
    { "code": "+886", "pattern": "# #### ####" },
    // 9
    { "code": "+90", "pattern": "### ### ####" },
    { "code": "+91", "pattern": "#### ### ###" },
    { "code": "+92", "pattern": "### ### ####" },
    { "code": "+93", "pattern": "## ### ####" },
    { "code": "+94", "pattern": "## ### ####" },
    { "code": "+95", "pattern": "## ### ###" },
    { "code": "+95", "pattern": "### ###" },
    { "code": "+95", "pattern": "# ### ###" },
    { "code": "+960", "pattern": "### ####" },
    { "code": "+961", "pattern": "# ### ###" },
    { "code": "+961", "pattern": "## ### ###" },
    { "code": "+962", "pattern": "# #### ####" },
    { "code": "+963", "pattern": "## #### ###" },
    { "code": "+964", "pattern": "### ### ####" },
    { "code": "+965", "pattern": "#### ####" },
    { "code": "+966", "pattern": "# ### ####" },
    { "code": "+966", "pattern": "5 #### ####" },
    { "code": "+967", "pattern": "# ### ###" },
    { "code": "+967", "pattern": "## ### ###" },
    { "code": "+967", "pattern": "### ### ###" },
    { "code": "+968", "pattern": "## ### ###" },
    { "code": "+970", "pattern": "## ### ####" },
    { "code": "+971", "pattern": "# ### ####" },
    { "code": "+971", "pattern": "5# ### ####" },
    { "code": "+972", "pattern": "# ### ####" },
    { "code": "+972", "pattern": "5# ### ####" },
    { "code": "+973", "pattern": "#### ####" },
    { "code": "+974", "pattern": "#### ####" },
    { "code": "+975", "pattern": "# ### ###" },
    { "code": "+975", "pattern": "17 ### ###" },
    { "code": "+976", "pattern": "## ## ####" },
    { "code": "+977", "pattern": "## ### ###" },
    { "code": "+98", "pattern": "### ### ####" },
    { "code": "+992", "pattern": "## ### ####" },
    { "code": "+993", "pattern": "# ### ####" },
    { "code": "+994", "pattern": "## ### ## ##" },
    { "code": "+995", "pattern": "### ### ###" },
    { "code": "+996", "pattern": "### ### ###" },
    { "code": "+998", "pattern": "## ### ####" },
];


let inputPhone = inputs.input1.replace(/\D/g, ''); // Strip non-numeric characters
    let foundMask = null; // To hold the found mask object

    // Find the mask that matches the start of the input phone
    for (const mask of maskList) {
        let cleanCode = mask.code.replace(/\D/g, '');
        if (inputPhone.startsWith(cleanCode)) {
            foundMask = mask;
            break;
        }
    }

    // If a matching mask is found, apply it
    if (foundMask) {
        let formattedNumber = foundMask.code + " "; // Start with the country code
        let phoneWithoutCode = inputPhone.substring(foundMask.code.replace(/\D/g, '').length); // Remove country code part
        let pattern = foundMask.pattern;
        let patternIndex = 0;
        let phoneIndex = 0;

        // Apply the pattern
        while (phoneIndex < phoneWithoutCode.length && patternIndex < pattern.length) {
            if (pattern[patternIndex] === '#') {
                // If pattern character is a placeholder, replace it with actual phone number digit
                formattedNumber += phoneWithoutCode[phoneIndex];
                phoneIndex++;
            } else {
                // If pattern character is not a placeholder, keep it
                formattedNumber += pattern[patternIndex];
            }
            patternIndex++;
        }

        return formattedNumber;
    }

    // No matching pattern found or other failure, return input as is
    return inputs.input1;
}

return { result: maskPhoneNumber(inputs) }
